---
- name: Copy nginx source to tmp
  copy:
    src: nginx-{{ version }}
    dest: tmp

- name: Running ./configure for nginx
  command: 'autoreconf -f -i'
  args:
    chdir: tmp/nginx-{{ version }}

- name: Running ./configure for nginx
  command: './configure'
  args:
    chdir: tmp/nginx-{{ version }}

- name: Running make for nginx
  command: 'make'
  args:
    chdir: tmp/nginx-{{ version }}

- name: Running make install for nginx
  become: yes
  command: 'make install'
  args:
    chdir: tmp/nginx-{{ version }}

- name: Clean nginx path
  file:
    state: absent
    path: tmp/nginx-{{ version }}
