---
- name: Extract pcre-{{ pcre_version }}.tar.gz into /usr/local
  ansible.builtin.unarchive:
    src: pcre-{{ pcre_version }}.tar.gz
    dest: /usr/local

- name: Set permission to for pcre for configure
  ansible.builtin.file:
    mode: '0750'
    path: /usr/local/pcre-{{ pcre_version }}/configure

- name: autoreconf ./configure for pcre
  become: yes
  command: 'autoreconf -f -i'
  args:
    chdir: /usr/local/pcre-{{ pcre_version }}

- name: Running ./configure for pcre
  become: yes
  command: './configure'
  args:
    chdir: /usr/local/pcre-{{ pcre_version }}

- name: Running make for pcre
  become: yes
  command: 'make'
  args:
    chdir: /usr/local/pcre-{{ pcre_version }}

- name: Running make install for pcre
  become: yes
  command: 'make install'
  args:
    chdir: /usr/local/pcre-{{ pcre_version }}
    
