---
- name: Extract zlib-{{ zlib_version }}.tar.gz into /usr/local
  ansible.builtin.unarchive:
    src: zlib-{{ zlib_version }}.tar.gz
    dest: /usr/local
  
- name: Set permission to for zlib for configure
  ansible.builtin.file:
    mode: '0750'
    path: /usr/local/zlib-{{ zlib_version }}/configure

- name: Running ./configure for zlib
  become: yes
  command: './configure'
  args:
    chdir: /usr/local/zlib-{{ zlib_version }}

- name: Running make for zlib
  become: yes
  command: 'make'
  args:
    chdir: /usr/local/zlib-{{ zlib_version }}

- name: Running make install for zlib
  become: yes
  command: 'make install'
  args:
    chdir: /usr/local/zlib-{{ zlib_version }}

