--
- name: Copy openssl source to tmp
  copy:
    src: openssl-{{ version }}
    dest: tmp

- name: Running ./configure for openssl
  command: 'autoreconf -f -i'
  args:
    chdir: tmp/openssl-{{ version }}

- name: Running ./configure for openssl
  command: './configure'
  args:
    chdir: tmp/openssl-{{ version }}

- name: Running make for openssl
  command: 'make'
  args:
    chdir: tmp/openssl-{{ version }}

- name: Running make install for openssl
  become: yes
  command: 'make install'
  args:
    chdir: tmp/openssl-{{ version }}

- name: Clean openssl path
  file:
    state: absent
    path: tmp/openssl-{{ version }}
