---
- name: Extract openssl-{{ openssl_version }}.tar.gz into /usr/local
  ansible.builtin.unarchive:
    src: openssl-{{ openssl_version }}.tar.gz
    dest: /usr/local

- name: Set permission to for openssl for configure
  ansible.builtin.file:
    mode: '0750'
    path: /usr/local/openssl-{{ openssl_version }}/config

- name: Running ./config for openssl
  become: yes
  command: './config'
  args:
    chdir: /usr/local/openssl-{{ openssl_version }}

- name: Running make for openssl
  become: yes
  command: 'make'
  args:
    chdir: /usr/local/openssl-{{ openssl_version }}

- name: Running make install for openssl
  become: yes
  command: 'make install'
  args:
    chdir: /usr/local/openssl-{{ openssl_version }}

